chore: update workflows and improve changelog management

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -2,7 +2,7 @@ name: Release
 
 on:
   release:
-    types: [published]
+    types: [published, edited]
   workflow_dispatch:
     inputs:
       tag_name:
@@ -12,36 +12,48 @@ on:
 
 jobs:
   release_on_thunderstore:
+    if: |
+      github.event_name == 'workflow_dispatch' ||
+      github.event.action == 'published' ||
+      (github.event.action == 'edited' && github.event.release.prerelease == false)
     env:
       RELEASE_TAG: ${{ github.event.inputs.tag_name || github.event.release.tag_name }}
     runs-on: ubuntu-latest
+
     steps:
       - name: Checkout
         uses: actions/checkout@v3
         with:
           fetch-depth: 0
           submodules: recursive
-      - name: Setup .NET
-        uses: actions/setup-dotnet@v2
-        with:
-          dotnet-version: 6.0.x
-      - name: Install GitVersion
-        uses: gittools/actions/gitversion/setup@v0.9.7
-        with:
-          versionSpec: "5.x"
-      - name: Determine Version
-        uses: gittools/actions/gitversion/execute@v0.9.7
-        with:
-          additionalArguments: '/overrideconfig "mode=Mainline" /overrideconfig "next-version=2.0.0"'
+
+      - name: Get the last release tag
+        id: get_last_release
+        run: |
+          LAST_TAG=$(git describe --tags --abbrev=0)
+          echo "LAST_TAG=${LAST_TAG}" >> $GITHUB_ENV
+          echo "::set-output name=last_tag::${LAST_TAG}"
+
+      - name: Check if LAST_TAG equals RELEASE_TAG
+        if: github.event.action == 'edited'
+        run: |
+          if [ ${{ env.LAST_TAG }} != ${{ env.RELEASE_TAG }} ]; then
+            echo "Error: LAST_TAG (${{ env.LAST_TAG }}) does not match RELEASE_TAG (${{ env.RELEASE_TAG }})"
+            exit 1
+          fi
+
       - name: Download Release
-        run: gh release download ${{ env.RELEASE_TAG }} -D ./dist
+        run: gh release download v${{ env.RELEASE_TAG }} -D ./dist
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
       - name: Install tcli
         run: dotnet tool install --global tcli
+
       - name: Run tcli
-        run: tcli publish --token ${{ secrets.THUNDERSTORE_KEY }} --package-version ${RELEASE_TAG:1}
+        run: tcli publish --token ${{ secrets.THUNDERSTORE_KEY }} --package-version ${{ env.RELEASE_TAG }}
+
       - name: Upload a Build Artifact
-        uses: actions/upload-artifact@v3.1.0
+        uses: actions/upload-artifact@v4
         with:
           path: ./build
